services:
  board-service:
    build: .
    image: choijm98/backend:v1
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:mysql://host.docker.internal:3306/test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=utf8
      DB_USERNAME: root
      DB_PASSWORD: "0000"
      JAVA_OPTS: "-Xms256m -Xmx512m"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

